import React, { useState, useEffect } from 'react';
import Head from 'next/head'

import styles from './PageContainer.module.css';

import Navbar from '@/components/Navbar/Navbar';

export default function PageContainer(props) {

    const { children } = props;

    return (
        <>
            <Head>
                <title>Nautical</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={styles.main}>
                {children}
            </div>
        </>
    )
}